title: "Nelson Sameul Professional Portfolio"
description: "Cyber Security Engineer | Ethical Hacker | Digital Forensics Practitioner"
url: "https://nelsonsamuell.github.io"
baseurl: ""
remote theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
sass:
  style: compressed

# Include custom CSS
include:
  - assets/css/custom.css
  - _includes/head/custom.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Nelson Samuel"
  avatar: "/images/profile.jpg"
  bio: "Cyber Security Professional | Ethical Hacker | Digital Forensics Practitioner"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-link"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"

nav:
  - title: "Home"
    url: /
  - title: "Resume"
    url: /resume
  - title: "Projects"
    url: /projects
  - title: "Lab Challenges"
    url: /labchallenges
  - title: "Contact"
    url: /contact

# Custom Dark Styling Fixes
# (Ensures text contrast remains clear and consistent)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      share: false
      related: false

